### PR TITLE
Updated the iot-device-sdk-embedded-c submodule to the latest 'master… (CA-44)

### PR DESCRIPTION
**Pull request by csobrinho**
…' and updated the port sources.

### CODE REVIEW

**Comment by csobrinho** [comment]
Could you confirm if `port/src/iotc_bsp_io_fs_posix.c` is necessary or correct for ESP-IDF? Thank you

**Comment by csobrinho** [comment]
Friendly ping.

**Comment by Alvin1Zhang** [comment]
@csobrinho Thanks for the contribution and sorry for late reply.

**Comment by meltdown03** [comment]
This works fine for me on my ESP32-S2 and IDF 4.2-dev (master branch). Hopefully it gets merged.

**Comment by meltdown03** [comment]
The updated iot-device-sdk-embedded-c submodule handles wildcards (#) in subscriptions differently. This causes the `{"outlet": 1}` command to fail the `if (strcmp(subscription_topic_command, params->message.topic) == 0)` test.

The `params->message.topic` ends up without the "/#". 
I just created another char* without the ending and use that for the comparison so it works again.

**Comment by hagronnestad** [comment]
Good PR! 👍 Would it be possible to get this PR verified by Espressif and merged?

**Comment by shahpiyushv** [comment]
Sorry for the delay from our side. We will start the review internally and try to get this in asap.

**Comment by hagronnestad** [comment]
Any progress?

**Comment by shahpiyushv** [comment]
@csobrinho Thanks for the contribution, and sorry for the delay. This has now been merged. @hagronnestad , thanks for your patience.

**Comment by hagronnestad** [comment]
Very good, thank you!

**Comment by csobrinho** [comment]
Awesome, thanks!

**Pull request merged**
